language: swift
osx_image: xcode10.1

xcode_project: ReduxMovieDB.xcworkspace
xcode_scheme: ReduxMovieDBTests

cache:
  - bundler

before_install:
  - bundle install
  - bundle update

script:
    - bundle exec fastlane test